# This workflow will install Python dependencies, run tests and lint
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Check Black

on:
  push:
    branches:
      - "master"
      - "development"
  pull_request:

jobs:
  check-black:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.8"

    steps:
      - uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4.0.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e . -r requirements-test.txt
      - name: Black pyvoip
        run: black --check pyvoip
      - name: Black tests
        run: black --check tests
